package client

var errors = []string{
	"CUBE_OAUTH2_ERR_OK",
	"CUBE_OAUTH2_ERR_TOKEN_NOT_FOUND",
	"CUBE_OAUTH2_ERR_DB_ERROR",
	"CUBE_OAUTH2_ERR_UNKNOWN_MSG",
	"CUBE_OAUTH2_ERR_BAD_PACKET",
	"CUBE_OAUTH2_ERR_BAD_CLIENT",
	"CUBE_OAUTH2_ERR_BAD_SCOPE",
}
